[{
  "id":1,
  "pid":0,
  "name":"根模块",
  "status":false
},{
  "id":2,
  "pid":1,
  "name":"系统管理",
  "status":true
},{
  "id":21,
  "pid":2,
  "name":"用户管理",
  "status":false,
  "power": [
      {"id":211,"text":"增加","status":true},
      {"id":212,"text":"修改","status":true},
      {"id":213,"text":"删除","status":true},
      {"id":214,"text":"重置密码","status":true},
      {"id":215,"text":"更新状态","status":true},
      {"id":216,"text":"设置权限","status":true}
    ]
},{
  "id":22,
  "pid":2,
  "name":"角色管理",
  "status":true,
  "power": [
      {"id":221,"text":"查看","status":true},
      {"id":222,"text":"增加","status":true},
      {"id":223,"text":"修改","status":true},
      {"id":224,"text":"删除","status":true},
      {"id":225,"text":"设置权限","status":true}
    ]
},{
  "id":23,
  "pid":2,
  "name":"模块管理",
  "status":true,
  "power": [
      {"id":231,"text":"查看","status":true},
      {"id":232,"text":"增加","status":false},
      {"id":233,"text":"修改","status":true},
      {"id":234,"text":"删除","status":true}
    ]
},{
  "id":24,
  "pid":2,
  "name":"日志管理",
  "status":true,
  "power": [
      {"id":241,"text":"查看","status":true},
      {"id":242,"text":"删除","status":true}
    ]
},{
  "id":3,
  "pid":1,
  "name":"功能管理"
},{
  "id":31,
  "pid":3,
  "name":"功能1",
  "status":true,
  "power": [
      {"id":311,"text":"查看","status":false},
      {"id":312,"text":"增加","status":true},
      {"id":313,"text":"修改","status":true},
      {"id":314,"text":"删除","status":false}
    ]
},{
  "id":32,
  "pid":3,
  "name":"功能2",
  "status":true,
  "power": [
      {"id":321,"text":"查看","status":true},
      {"id":322,"text":"增加","status":true},
      {"id":323,"text":"修改","status":true},
      {"id":324,"text":"删除","status":true}
    ]
}]